# Lecture 9: Machine Learning

In [1]:
# Install the package numpy and scikit-learn


In [1]:
# pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy>=1.13.3 in c:\users\chard\anaconda3\lib\site-packages (from scikit-learn) (1.23.3)



In [3]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
#import the packages (numpy and linear_model from scikit)

import numpy as np

## Introduction to numpy

In [2]:
#Create your first numpy array in 1 dimension

array = np.array([1,2,3,4,5,6])
print(array)

[1 2 3 4 5 6]


In [3]:
#Create your first 2 dimensionnal arry
l = [[1, 2, 3], [4, 5, 6]]
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print('-'*20)
print(l)


[[1 2 3]
 [4 5 6]]
--------------------
[[1, 2, 3], [4, 5, 6]]


In [4]:
#getting access to numpy array items
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array[0][1])

2


In [5]:
#the copy and the view
list0 = [1, 2, 3]
list1 = list0.copy()
list1[0] = 55
print(list1)
print(list0)


[55, 2, 3]
[1, 2, 3]


In [6]:
#the copy and the view
arr0 = np.array([1, 2, 3])
arr1 = arr0.view()  # view будет зависить потом, типа если поменяем arr1 то значит и arr0 поменяется
arr2 = arr0.copy() # copy просто копирует , и не будет зависить
arr1[1]= 50
# arr2[1] = 50000
print(arr0)
print(arr1)
print(arr2)


[ 1 50  3]
[ 1 50  3]
[1 2 3]


In [7]:
array = np.array([[1, 20000000, 3], [4, 5, 6]])
print(array)

[[       1 20000000        3]
 [       4        5        6]]


In [8]:
#The shape of an array
# размер array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array.shape) 

(8,)


In [10]:
#reshape your array from 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((3,2)))

# 3 строчки и 2 колоны 

[[1 2]
 [3 4]
 [5 6]]


In [11]:
#reshape your array from 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((6,1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
#reshape your array from 1D to another D (with -1)
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((-1,2)))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
#reshape your array from 1D to another D (with -1)
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((-1,1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [14]:
#The hstack
array0 = np.array([1, 2, 3, 4, 5, 6])
array0 = array.reshape((-1,1))
array1 = np.array([7, 8, 9, 10, 11, 12])
array1 = array1.reshape((-1,1))
print(array0)
print('-'*20)
print(array1)
print('-'*20)
print(np.hstack([array0, array1]))

# hstack 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
--------------------
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [15]:
#The avantage of numpy, the use of array for addition or multiplication for example
l = [1, 2, 3, 4]
arr = np.array([1,2,3,4])
# print(l +2 )
print(arr +2 )
print(arr *2 )
print(l + l )
print(arr + arr)

[3 4 5 6]
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [16]:
#YOUR TURN (10 minutes)
#Change this array [1,5,9,31,45,78]
#into this one:
#[[1 5],
#[9 31],
#[45 78]]
arr = np.array([1,5,9,31,45,78])
print(arr.reshape((3,2)))
print(arr.reshape((-1,2)))
print(arr.reshape((3,-1)))

[[ 1  5]
 [ 9 31]
 [45 78]]
[[ 1  5]
 [ 9 31]
 [45 78]]
[[ 1  5]
 [ 9 31]
 [45 78]]
